export const payments = [
    {
        id: "baf914e1",
        amount: 417,
        name: "Tammy",
        status: "completed",
        email: "jillperry@yahoo.com",
    },
    {
        id: "d3864432",
        amount: 247,
        name: "Michael",
        status: "processing",
        email: "randykelly@spencer-bradley.com",
    },
    {
        id: "814ab166",
        amount: 446,
        name: "Stacy",
        status: "processing",
        email: "sherrywhite@gmail.com",
    },
    {
        id: "5062da27",
        amount: 124,
        name: "Daniel",
        status: "pending",
        email: "connermichael@myers.com",
    },
    {
        id: "d2a48ea8",
        amount: 137,
        name: "Erika",
        status: "processing",
        email: "jeremy30@yahoo.com",
    },
    {
        id: "a6b9e02d",
        amount: 265,
        name: "Travis",
        status: "failed",
        email: "donnasmith@gmail.com",
    },
    {
        id: "cf13e427",
        amount: 492,
        name: "Jessica",
        status: "completed",
        email: "kevin87@yahoo.com",
    },
    {
        id: "67b1c2a4",
        amount: 152,
        name: "Brian",
        status: "pending",
        email: "brownchristina@hotmail.com",
    },
    {
        id: "7b28a41d",
        amount: 384,
        name: "Laura",
        status: "processing",
        email: "shannon72@young.com",
    },
    {
        id: "6e82c1fa",
        amount: 214,
        name: "David",
        status: "completed",
        email: "anthonyjohnson@hotmail.com",
    },
    {
        id: "3a7d6e94",
        amount: 358,
        name: "Amber",
        status: "pending",
        email: "paulwatson@gmail.com",
    },
    {
        id: "fc4e20a8",
        amount: 291,
        name: "George",
        status: "failed",
        email: "gregoryhill@powell.com",
    },
    {
        id: "e9a35b12",
        amount: 175,
        name: "Emily",
        status: "completed",
        email: "davidmartin@yahoo.com",
    },
    {
        id: "19c7de6a",
        amount: 399,
        name: "Matthew",
        status: "processing",
        email: "ryanrivera@gmail.com",
    },
    {
        id: "93e0c84b",
        amount: 264,
        name: "Holly",
        status: "pending",
        email: "alexandermatthews@yahoo.com",
    },
    {
        id: "fa7d3249",
        amount: 338,
        name: "Joshua",
        status: "completed",
        email: "bradleybrown@ortega.com",
    },
    {
        id: "52b3d1a7",
        amount: 176,
        name: "Kelly",
        status: "failed",
        email: "stephanie91@hotmail.com",
    },
    {
        id: "ca48d06f",
        amount: 283,
        name: "Anthony",
        status: "processing",
        email: "michaelschmidt@yahoo.com",
    },
    {
        id: "b4f62d8c",
        amount: 128,
        name: "Megan",
        status: "completed",
        email: "sharonbrown@gmail.com",
    },
    {
        id: "9e8d02f7",
        amount: 307,
        name: "Jacob",
        status: "pending",
        email: "brianallen@yahoo.com",
    },
    {
        id: "0c4e18a5",
        amount: 497,
        name: "Olivia",
        status: "processing",
        email: "courtneyfisher@gmail.com",
    },
    {
        id: "a47d6c1e",
        amount: 273,
        name: "John",
        status: "failed",
        email: "stevenward@hotmail.com",
    },
    {
        id: "e02a3d71",
        amount: 189,
        name: "Natalie",
        status: "completed",
        email: "zacharyscott@gmail.com",
    },
    {
        id: "d4f7a92c",
        amount: 355,
        name: "Andrew",
        status: "pending",
        email: "matthewramirez@hotmail.com",
    },
    {
        id: "6fa3c918",
        amount: 221,
        name: "Rachel",
        status: "processing",
        email: "christopher23@yahoo.com",
    },
    {
        id: "fb49d803",
        amount: 333,
        name: "Aaron",
        status: "completed",
        email: "philipscott@gmail.com",
    },
    {
        id: "28e3af5c",
        amount: 142,
        name: "Victoria",
        status: "failed",
        email: "elizabethwright@yahoo.com",
    },
    {
        id: "14b7c9e6",
        amount: 368,
        name: "Brandon",
        status: "completed",
        email: "robertclark@hotmail.com",
    },
    {
        id: "9c4a2e8f",
        amount: 216,
        name: "Amanda",
        status: "pending",
        email: "samanthaperez@gmail.com",
    },
    {
        id: "7fa6d4c2",
        amount: 299,
        name: "Ethan",
        status: "processing",
        email: "jasonparker@hotmail.com",
    },
    {
        id: "37c1f92a",
        amount: 254,
        name: "Ashley",
        status: "completed",
        email: "julieortiz@yahoo.com",
    },
    {
        id: "82f4a56d",
        amount: 121,
        name: "Christopher",
        status: "failed",
        email: "charlesking@gmail.com",
    },
    {
        id: "6c5e93a1",
        amount: 445,
        name: "Brittany",
        status: "pending",
        email: "susanross@hotmail.com",
    },
    {
        id: "fa6d1c23",
        amount: 275,
        name: "Kevin",
        status: "completed",
        email: "andersondiana@gmail.com",
    },
    {
        id: "3f8c1b7e",
        amount: 398,
        name: "Samantha",
        status: "processing",
        email: "patrickmorris@hotmail.com",
    },
    {
        id: "29f4d8b1",
        amount: 163,
        name: "Zachary",
        status: "pending",
        email: "danieljackson@yahoo.com",
    },
    {
        id: "84b5c2e6",
        amount: 284,
        name: "Molly",
        status: "completed",
        email: "nicholaslong@gmail.com",
    },
    {
        id: "48c6d3f9",
        amount: 356,
        name: "Justin",
        status: "failed",
        email: "whitneyedwards@yahoo.com",
    },
    {
        id: "e5a9b72d",
        amount: 222,
        name: "Stephanie",
        status: "completed",
        email: "georgewood@hotmail.com",
    },
    {
        id: "c9d6e728",
        amount: 331,
        name: "Kyle",
        status: "processing",
        email: "scottjohnson@yahoo.com",
    },
    {
        id: "1b2c4d5f",
        amount: 187,
        name: "Courtney",
        status: "pending",
        email: "heatherhall@gmail.com",
    },
    {
        id: "72f9a4e3",
        amount: 243,
        name: "Eric",
        status: "completed",
        email: "jefferynelson@yahoo.com",
    },
    {
        id: "5c7d9f12",
        amount: 168,
        name: "Melissa",
        status: "processing",
        email: "bethlewis@hotmail.com",
    },
    {
        id: "e13c2f9a",
        amount: 415,
        name: "Jason",
        status: "pending",
        email: "richardrobinson@gmail.com",
    },
    {
        id: "9f2e1c6b",
        amount: 281,
        name: "Nicole",
        status: "failed",
        email: "angelamorgan@yahoo.com",
    },
    {
        id: "c8d5b9f0",
        amount: 309,
        name: "Sean",
        status: "completed",
        email: "timothyjohnson@hotmail.com",
    },
    {
        id: "41e6a7c9",
        amount: 176,
        name: "Danielle",
        status: "pending",
        email: "mariarodriguez@gmail.com",
    },
    {
        id: "fb8c1d7a",
        amount: 390,
        name: "Patrick",
        status: "processing",
        email: "sharonjenkins@yahoo.com",
    },
    {
        id: "6a9d3f28",
        amount: 205,
        name: "Katherine",
        status: "completed",
        email: "markgonzalez@hotmail.com",
    },
];
